name: Node.js CI

on: [push]

jobs:
  metascape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: npm install puppeteer
    - run: mkdir output
    - run: node metascape/index.js
    - run: ls
    - uses: actions/upload-artifact@v1
      with:
        name: metascape
        path: output/
