name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: npm install puppeteer
    - run: node js/test.js
    - run: ls
    - uses: actions/upload-artifact@v1
      with:
        path: output/hn.pdf
